account_id = "d500fa18c226aa3c452dac85ef7de1a5"
compatibility_date = "2022-02-21"
compatibility_flags = ["streams_enable_constructors"]
main = "src/index.ts"
name = "my-worker-dev"
workers_dev = true

[[migrations]]
new_classes = ["WsConnection"]
tag = "v1"

[[d1_databases]]
binding = "SUBSCRIPTIONS_DEV" # i.e. available in your Worker on env.DB
database_id = "cbcfa2b3-6731-44d1-8dee-74a9a964787d" 
database_name = "SUBSCRIPTIONS_DEV" 
migrations_dir = 'db/migrations' 
preview_database_id = "cbcfa2b3-6731-44d1-8dee-74a9a964787d" 

[miniflare]
durable_objects_persist = true

[durable_objects]
bindings = [{name = "WS_CONNECTION", class_name = "WsConnection"}]
#wrangler d1 migrations create <SUBSCRIPTIONS_DEV> "CREATE_SUBSCRIPTION_TABLE"
